name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main  # Escucha los cambios solo en la rama main

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_SALMON_MUD_0273E0310 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}  # Token usado para integraciones con GitHub
          action: "upload"
          ###### Configuración de Repositorio/Build - Ajusta estos valores a los requerimientos de tu app ######
          app_location: "src"  # Ruta donde está tu aplicación web estática
          api_location: "api"  # Ruta donde están tus funciones API
          output_location: ""  # Deja vacío si no hay paso de build
          ###### Fin de la Configuración de Repositorio/Build ######
